title: Introduction to Programming for Public Policy (30550)
author: James Saxon
author_email: jsaxon@uc
description: "Class Syllabus "
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
