title: Introduction to Programming for Public Policy (30550)
authors:
  JamesSaxon:
    name: Jamie Saxon
    display_name: Jamie Saxon
    email: jsaxon@uchicago.edu
    github: JamesSaxon
description: "Class Syllabus"
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
