title: Introduction to Programming for Public Policy (30550)
author:
  name: James Saxon
  email: jsaxon@uchicago.edu
description: "Class Syllabus "
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
